/* Generated by Yosys 0.66+4 (git sha1 8125af88d-dirty, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

module adder(srca, srcb, cin, is_signed, result, cout, zero_f, ov_f);
  input [7:0] srca;
  wire [7:0] srca;
  input [7:0] srcb;
  wire [7:0] srcb;
  input cin;
  wire cin;
  input is_signed;
  wire is_signed;
  output [7:0] result;
  wire [7:0] result;
  output cout;
  wire cout;
  output zero_f;
  wire zero_f;
  output ov_f;
  wire ov_f;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire \full_adders[0].adder.result ;
  wire \full_adders[1].adder.result ;
  wire \full_adders[2].adder.result ;
  wire \full_adders[3].adder.result ;
  wire \full_adders[4].adder.result ;
  wire \full_adders[5].adder.result ;
  wire \full_adders[6].adder.result ;
  wire \full_adders[7].adder.result ;
  INV_X1 _045_ (
    .A(srcb[2]),
    .ZN(_000_)
  );
  INV_X1 _046_ (
    .A(srca[2]),
    .ZN(_001_)
  );
  INV_X1 _047_ (
    .A(srca[3]),
    .ZN(_002_)
  );
  INV_X1 _048_ (
    .A(srcb[5]),
    .ZN(_003_)
  );
  INV_X1 _049_ (
    .A(srcb[6]),
    .ZN(_004_)
  );
  INV_X1 _050_ (
    .A(srca[6]),
    .ZN(_005_)
  );
  INV_X1 _051_ (
    .A(srca[1]),
    .ZN(_006_)
  );
  INV_X1 _052_ (
    .A(srcb[1]),
    .ZN(_007_)
  );
  NOR2_X1 _053_ (
    .A1(cin),
    .A2(srcb[0]),
    .ZN(_008_)
  );
  AOI21_X1 _054_ (
    .A(srca[0]),
    .B1(cin),
    .B2(srcb[0]),
    .ZN(_009_)
  );
  NOR2_X1 _055_ (
    .A1(_008_),
    .A2(_009_),
    .ZN(_010_)
  );
  OAI21_X1 _056_ (
    .A(_007_),
    .B1(_008_),
    .B2(_009_),
    .ZN(_011_)
  );
  NOR3_X1 _057_ (
    .A1(_007_),
    .A2(_008_),
    .A3(_009_),
    .ZN(_012_)
  );
  NAND2_X1 _058_ (
    .A1(srcb[1]),
    .A2(_010_),
    .ZN(_013_)
  );
  NAND2_X1 _059_ (
    .A1(srca[1]),
    .A2(_011_),
    .ZN(_014_)
  );
  NAND2_X1 _060_ (
    .A1(_013_),
    .A2(_014_),
    .ZN(_015_)
  );
  AOI21_X1 _061_ (
    .A(_012_),
    .B1(_011_),
    .B2(srca[1]),
    .ZN(_016_)
  );
  NAND2_X1 _062_ (
    .A1(_000_),
    .A2(_016_),
    .ZN(_017_)
  );
  OAI21_X1 _063_ (
    .A(_001_),
    .B1(_016_),
    .B2(_000_),
    .ZN(_018_)
  );
  AOI21_X1 _064_ (
    .A(srcb[3]),
    .B1(_017_),
    .B2(_018_),
    .ZN(_019_)
  );
  NAND3_X1 _065_ (
    .A1(srcb[3]),
    .A2(_017_),
    .A3(_018_),
    .ZN(_020_)
  );
  OAI21_X1 _066_ (
    .A(_020_),
    .B1(_019_),
    .B2(_002_),
    .ZN(_021_)
  );
  NOR2_X1 _067_ (
    .A1(srcb[4]),
    .A2(_021_),
    .ZN(_022_)
  );
  AOI21_X1 _068_ (
    .A(srca[4]),
    .B1(_021_),
    .B2(srcb[4]),
    .ZN(_023_)
  );
  OAI21_X1 _069_ (
    .A(_003_),
    .B1(_022_),
    .B2(_023_),
    .ZN(_024_)
  );
  NOR3_X1 _070_ (
    .A1(_003_),
    .A2(_022_),
    .A3(_023_),
    .ZN(_025_)
  );
  AOI21_X1 _071_ (
    .A(_025_),
    .B1(_024_),
    .B2(srca[5]),
    .ZN(_026_)
  );
  NOR2_X1 _072_ (
    .A1(_004_),
    .A2(_026_),
    .ZN(_027_)
  );
  XNOR2_X1 _073_ (
    .A(srcb[6]),
    .B(_026_),
    .ZN(_028_)
  );
  AOI21_X1 _074_ (
    .A(_005_),
    .B1(_026_),
    .B2(_004_),
    .ZN(_029_)
  );
  NOR2_X1 _075_ (
    .A1(_027_),
    .A2(_029_),
    .ZN(_030_)
  );
  XNOR2_X1 _076_ (
    .A(_005_),
    .B(_028_),
    .ZN(\full_adders[6].adder.result )
  );
  NOR2_X1 _077_ (
    .A1(srca[7]),
    .A2(srcb[7]),
    .ZN(_031_)
  );
  NAND2_X1 _078_ (
    .A1(srca[7]),
    .A2(srcb[7]),
    .ZN(_032_)
  );
  XOR2_X1 _079_ (
    .A(srca[7]),
    .B(srcb[7]),
    .Z(_033_)
  );
  AOI21_X1 _080_ (
    .A(_031_),
    .B1(_032_),
    .B2(_030_),
    .ZN(cout)
  );
  XNOR2_X1 _081_ (
    .A(_030_),
    .B(_033_),
    .ZN(\full_adders[7].adder.result )
  );
  XNOR2_X1 _082_ (
    .A(srcb[4]),
    .B(_021_),
    .ZN(_034_)
  );
  XNOR2_X1 _083_ (
    .A(srca[4]),
    .B(_034_),
    .ZN(\full_adders[4].adder.result )
  );
  NAND2_X1 _084_ (
    .A1(srca[5]),
    .A2(_025_),
    .ZN(_035_)
  );
  OAI21_X1 _085_ (
    .A(_026_),
    .B1(_024_),
    .B2(srca[5]),
    .ZN(_036_)
  );
  NAND2_X1 _086_ (
    .A1(_035_),
    .A2(_036_),
    .ZN(\full_adders[5].adder.result )
  );
  XNOR2_X1 _087_ (
    .A(_000_),
    .B(_016_),
    .ZN(_037_)
  );
  XNOR2_X1 _088_ (
    .A(srca[2]),
    .B(_037_),
    .ZN(\full_adders[2].adder.result )
  );
  AND2_X1 _089_ (
    .A1(_002_),
    .A2(_019_),
    .ZN(_038_)
  );
  OAI22_X1 _090_ (
    .A1(_002_),
    .A2(_020_),
    .B1(_021_),
    .B2(_038_),
    .ZN(\full_adders[3].adder.result )
  );
  NOR3_X1 _091_ (
    .A1(srca[0]),
    .A2(cin),
    .A3(srcb[0]),
    .ZN(_039_)
  );
  NAND3_X1 _092_ (
    .A1(srca[0]),
    .A2(cin),
    .A3(srcb[0]),
    .ZN(_040_)
  );
  OAI21_X1 _093_ (
    .A(_040_),
    .B1(_039_),
    .B2(_010_),
    .ZN(\full_adders[0].adder.result )
  );
  NOR2_X1 _094_ (
    .A1(srca[1]),
    .A2(_011_),
    .ZN(_041_)
  );
  OAI22_X1 _095_ (
    .A1(_006_),
    .A2(_013_),
    .B1(_015_),
    .B2(_041_),
    .ZN(\full_adders[1].adder.result )
  );
  OR4_X1 _096_ (
    .A1(\full_adders[6].adder.result ),
    .A2(\full_adders[4].adder.result ),
    .A3(\full_adders[0].adder.result ),
    .A4(\full_adders[1].adder.result ),
    .ZN(_042_)
  );
  OR3_X1 _097_ (
    .A1(\full_adders[5].adder.result ),
    .A2(\full_adders[2].adder.result ),
    .A3(\full_adders[3].adder.result ),
    .ZN(_043_)
  );
  NOR3_X1 _098_ (
    .A1(\full_adders[7].adder.result ),
    .A2(_042_),
    .A3(_043_),
    .ZN(zero_f)
  );
  OAI21_X1 _099_ (
    .A(is_signed),
    .B1(_027_),
    .B2(_029_),
    .ZN(_044_)
  );
  MUX2_X1 _100_ (
    .A(_031_),
    .B(cout),
    .S(_044_),
    .Z(ov_f)
  );
  assign result = { \full_adders[7].adder.result , \full_adders[6].adder.result , \full_adders[5].adder.result , \full_adders[4].adder.result , \full_adders[3].adder.result , \full_adders[2].adder.result , \full_adders[1].adder.result , \full_adders[0].adder.result  };
endmodule
