/* Generated by Yosys 0.66+4 (git sha1 8125af88d-dirty, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "convert_to_v/rca.v:1.1-38.10" *)
module adder(srca, srcb, cin, is_signed, result, cout, zero_f, ov_f);
  (* src = "convert_to_v/rca.v:12.27-12.31" *)
  input [7:0] srca;
  wire [7:0] srca;
  (* src = "convert_to_v/rca.v:13.27-13.31" *)
  input [7:0] srcb;
  wire [7:0] srcb;
  (* src = "convert_to_v/rca.v:14.13-14.16" *)
  input cin;
  wire cin;
  (* src = "convert_to_v/rca.v:15.13-15.22" *)
  input is_signed;
  wire is_signed;
  (* src = "convert_to_v/rca.v:16.28-16.34" *)
  output [7:0] result;
  wire [7:0] result;
  (* src = "convert_to_v/rca.v:17.14-17.18" *)
  output cout;
  wire cout;
  (* src = "convert_to_v/rca.v:18.14-18.20" *)
  output zero_f;
  wire zero_f;
  (* src = "convert_to_v/rca.v:19.14-19.18" *)
  output ov_f;
  wire ov_f;
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "convert_to_v/rca.v:20.17-20.18" *)
  wire [8:0] c;
  sky130_fd_sc_hd__nand2_1 _3_ (
    .A(is_signed),
    .B(c[7]),
    .Y(_0_)
  );
  sky130_fd_sc_hd__xnor2_1 _4_ (
    .A(cout),
    .B(_0_),
    .Y(ov_f)
  );
  sky130_fd_sc_hd__or4_1 _5_ (
    .A(result[6]),
    .B(result[7]),
    .C(result[4]),
    .D(result[5]),
    .X(_1_)
  );
  sky130_fd_sc_hd__or4_1 _6_ (
    .A(result[2]),
    .B(result[3]),
    .C(result[0]),
    .D(result[1]),
    .X(_2_)
  );
  sky130_fd_sc_hd__nor2_1 _7_ (
    .A(_1_),
    .B(_2_),
    .Y(zero_f)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[0].adder  (
    .a(srca[0]),
    .b(srcb[0]),
    .cin(cin),
    .cout(c[1]),
    .result(result[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[1].adder  (
    .a(srca[1]),
    .b(srcb[1]),
    .cin(c[1]),
    .cout(c[2]),
    .result(result[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[2].adder  (
    .a(srca[2]),
    .b(srcb[2]),
    .cin(c[2]),
    .cout(c[3]),
    .result(result[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[3].adder  (
    .a(srca[3]),
    .b(srcb[3]),
    .cin(c[3]),
    .cout(c[4]),
    .result(result[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[4].adder  (
    .a(srca[4]),
    .b(srcb[4]),
    .cin(c[4]),
    .cout(c[5]),
    .result(result[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[5].adder  (
    .a(srca[5]),
    .b(srcb[5]),
    .cin(c[5]),
    .cout(c[6]),
    .result(result[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[6].adder  (
    .a(srca[6]),
    .b(srcb[6]),
    .cin(c[6]),
    .cout(c[7]),
    .result(result[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[7].adder  (
    .a(srca[7]),
    .b(srcb[7]),
    .cin(c[7]),
    .cout(cout),
    .result(result[7])
  );
  assign { c[8], c[0] } = { cout, cin };
endmodule

(* src = "convert_to_v/full_adder.v:1.1-15.10" *)
module full_adder(a, b, cin, result, cout);
  (* src = "convert_to_v/full_adder.v:8.13-8.14" *)
  input a;
  wire a;
  (* src = "convert_to_v/full_adder.v:9.13-9.14" *)
  input b;
  wire b;
  (* src = "convert_to_v/full_adder.v:10.13-10.16" *)
  input cin;
  wire cin;
  (* src = "convert_to_v/full_adder.v:11.14-11.20" *)
  output result;
  wire result;
  (* src = "convert_to_v/full_adder.v:12.14-12.18" *)
  output cout;
  wire cout;
  sky130_fd_sc_hd__maj3_1 _0_ (
    .A(cin),
    .B(a),
    .C(b),
    .X(cout)
  );
  sky130_fd_sc_hd__xor3_1 _1_ (
    .A(cin),
    .B(a),
    .C(b),
    .X(result)
  );
endmodule
