/* Generated by Yosys 0.66+4 (git sha1 8125af88d-dirty, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

module adder(srca, srcb, cin, is_signed, result, cout, zero_f, ov_f);
  input [15:0] srca;
  wire [15:0] srca;
  input [15:0] srcb;
  wire [15:0] srcb;
  input cin;
  wire cin;
  input is_signed;
  wire is_signed;
  output [15:0] result;
  wire [15:0] result;
  output cout;
  wire cout;
  output zero_f;
  wire zero_f;
  output ov_f;
  wire ov_f;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire \full_adders[0].adder.result ;
  wire \full_adders[10].adder.result ;
  wire \full_adders[11].adder.result ;
  wire \full_adders[12].adder.result ;
  wire \full_adders[13].adder.result ;
  wire \full_adders[14].adder.result ;
  wire \full_adders[15].adder.result ;
  wire \full_adders[1].adder.result ;
  wire \full_adders[2].adder.result ;
  wire \full_adders[3].adder.result ;
  wire \full_adders[4].adder.result ;
  wire \full_adders[5].adder.result ;
  wire \full_adders[6].adder.result ;
  wire \full_adders[7].adder.result ;
  wire \full_adders[8].adder.result ;
  wire \full_adders[9].adder.result ;
  INV_X1 _108_ (
    .A(srcb[4]),
    .ZN(_062_)
  );
  INV_X1 _109_ (
    .A(srca[4]),
    .ZN(_063_)
  );
  INV_X1 _110_ (
    .A(srcb[5]),
    .ZN(_064_)
  );
  INV_X1 _111_ (
    .A(srca[5]),
    .ZN(_065_)
  );
  INV_X1 _112_ (
    .A(srca[6]),
    .ZN(_066_)
  );
  INV_X1 _113_ (
    .A(srcb[7]),
    .ZN(_067_)
  );
  INV_X1 _114_ (
    .A(srca[7]),
    .ZN(_068_)
  );
  INV_X1 _115_ (
    .A(srca[8]),
    .ZN(_069_)
  );
  INV_X1 _116_ (
    .A(srca[9]),
    .ZN(_070_)
  );
  INV_X1 _117_ (
    .A(srca[10]),
    .ZN(_071_)
  );
  INV_X1 _118_ (
    .A(srcb[11]),
    .ZN(_072_)
  );
  INV_X1 _119_ (
    .A(srcb[12]),
    .ZN(_073_)
  );
  INV_X1 _120_ (
    .A(srca[12]),
    .ZN(_074_)
  );
  INV_X1 _121_ (
    .A(srca[13]),
    .ZN(_075_)
  );
  INV_X1 _122_ (
    .A(srca[2]),
    .ZN(_076_)
  );
  INV_X1 _123_ (
    .A(srca[3]),
    .ZN(_077_)
  );
  INV_X1 _124_ (
    .A(srca[0]),
    .ZN(_078_)
  );
  INV_X1 _125_ (
    .A(srca[1]),
    .ZN(_079_)
  );
  INV_X1 _126_ (
    .A(is_signed),
    .ZN(_080_)
  );
  INV_X1 _127_ (
    .A(srcb[3]),
    .ZN(_081_)
  );
  INV_X1 _128_ (
    .A(srcb[2]),
    .ZN(_082_)
  );
  INV_X1 _129_ (
    .A(srcb[1]),
    .ZN(_083_)
  );
  NAND2_X1 _130_ (
    .A1(cin),
    .A2(srcb[0]),
    .ZN(_084_)
  );
  NOR2_X1 _131_ (
    .A1(cin),
    .A2(srcb[0]),
    .ZN(_085_)
  );
  OAI21_X1 _132_ (
    .A(srca[0]),
    .B1(cin),
    .B2(srcb[0]),
    .ZN(_086_)
  );
  AOI21_X1 _133_ (
    .A(srca[0]),
    .B1(cin),
    .B2(srcb[0]),
    .ZN(_087_)
  );
  AND3_X1 _134_ (
    .A1(_083_),
    .A2(_084_),
    .A3(_086_),
    .ZN(_088_)
  );
  OAI21_X1 _135_ (
    .A(_083_),
    .B1(_085_),
    .B2(_087_),
    .ZN(_089_)
  );
  NOR3_X1 _136_ (
    .A1(_083_),
    .A2(_085_),
    .A3(_087_),
    .ZN(_090_)
  );
  OR3_X1 _137_ (
    .A1(_083_),
    .A2(_085_),
    .A3(_087_),
    .ZN(_091_)
  );
  OAI21_X1 _138_ (
    .A(_091_),
    .B1(_088_),
    .B2(_079_),
    .ZN(_092_)
  );
  AOI21_X1 _139_ (
    .A(_090_),
    .B1(_089_),
    .B2(srca[1]),
    .ZN(_093_)
  );
  NOR2_X1 _140_ (
    .A1(srcb[2]),
    .A2(_092_),
    .ZN(_094_)
  );
  NAND2_X1 _141_ (
    .A1(_082_),
    .A2(_093_),
    .ZN(_095_)
  );
  AOI21_X1 _142_ (
    .A(srca[2]),
    .B1(srcb[2]),
    .B2(_092_),
    .ZN(_096_)
  );
  OAI21_X1 _143_ (
    .A(_076_),
    .B1(_082_),
    .B2(_093_),
    .ZN(_097_)
  );
  NOR3_X1 _144_ (
    .A1(_081_),
    .A2(_094_),
    .A3(_096_),
    .ZN(_098_)
  );
  NAND3_X1 _145_ (
    .A1(srcb[3]),
    .A2(_095_),
    .A3(_097_),
    .ZN(_099_)
  );
  AOI21_X1 _146_ (
    .A(srcb[3]),
    .B1(_095_),
    .B2(_097_),
    .ZN(_100_)
  );
  OAI21_X1 _147_ (
    .A(_081_),
    .B1(_094_),
    .B2(_096_),
    .ZN(_101_)
  );
  OAI21_X1 _148_ (
    .A(_101_),
    .B1(_098_),
    .B2(srca[3]),
    .ZN(_102_)
  );
  AOI21_X1 _149_ (
    .A(_100_),
    .B1(_099_),
    .B2(_077_),
    .ZN(_103_)
  );
  NOR2_X1 _150_ (
    .A1(_062_),
    .A2(_102_),
    .ZN(_104_)
  );
  NAND2_X1 _151_ (
    .A1(srcb[4]),
    .A2(_103_),
    .ZN(_105_)
  );
  AOI21_X1 _152_ (
    .A(_063_),
    .B1(_102_),
    .B2(_062_),
    .ZN(_106_)
  );
  OAI21_X1 _153_ (
    .A(srca[4]),
    .B1(_103_),
    .B2(srcb[4]),
    .ZN(_107_)
  );
  AOI21_X1 _154_ (
    .A(_064_),
    .B1(_105_),
    .B2(_107_),
    .ZN(_000_)
  );
  OAI21_X1 _155_ (
    .A(srcb[5]),
    .B1(_104_),
    .B2(_106_),
    .ZN(_001_)
  );
  NOR3_X1 _156_ (
    .A1(srcb[5]),
    .A2(_104_),
    .A3(_106_),
    .ZN(_002_)
  );
  NAND3_X1 _157_ (
    .A1(_064_),
    .A2(_105_),
    .A3(_107_),
    .ZN(_003_)
  );
  AOI21_X1 _158_ (
    .A(_002_),
    .B1(_001_),
    .B2(_065_),
    .ZN(_004_)
  );
  OR2_X1 _159_ (
    .A1(srcb[6]),
    .A2(_004_),
    .ZN(_005_)
  );
  OAI211_X1 _160_ (
    .A(srcb[6]),
    .B(_003_),
    .C1(_000_),
    .C2(srca[5]),
    .ZN(_006_)
  );
  NAND2_X1 _161_ (
    .A1(_066_),
    .A2(_006_),
    .ZN(_007_)
  );
  OAI21_X1 _162_ (
    .A(srca[6]),
    .B1(_004_),
    .B2(srcb[6]),
    .ZN(_008_)
  );
  AOI21_X1 _163_ (
    .A(_067_),
    .B1(_006_),
    .B2(_008_),
    .ZN(_009_)
  );
  NAND3_X1 _164_ (
    .A1(srcb[7]),
    .A2(_005_),
    .A3(_007_),
    .ZN(_010_)
  );
  AOI21_X1 _165_ (
    .A(srcb[7]),
    .B1(_005_),
    .B2(_007_),
    .ZN(_011_)
  );
  NAND3_X1 _166_ (
    .A1(_067_),
    .A2(_006_),
    .A3(_008_),
    .ZN(_012_)
  );
  AOI21_X1 _167_ (
    .A(_011_),
    .B1(_010_),
    .B2(_068_),
    .ZN(_013_)
  );
  OR2_X1 _168_ (
    .A1(srcb[8]),
    .A2(_013_),
    .ZN(_014_)
  );
  OAI211_X1 _169_ (
    .A(srcb[8]),
    .B(_012_),
    .C1(_009_),
    .C2(srca[7]),
    .ZN(_015_)
  );
  NAND2_X1 _170_ (
    .A1(_069_),
    .A2(_015_),
    .ZN(_016_)
  );
  NAND3_X1 _171_ (
    .A1(srcb[9]),
    .A2(_014_),
    .A3(_016_),
    .ZN(_017_)
  );
  AOI21_X1 _172_ (
    .A(srcb[9]),
    .B1(_014_),
    .B2(_016_),
    .ZN(_018_)
  );
  AOI21_X1 _173_ (
    .A(_018_),
    .B1(_017_),
    .B2(_070_),
    .ZN(_019_)
  );
  OR2_X1 _174_ (
    .A1(srcb[10]),
    .A2(_019_),
    .ZN(_020_)
  );
  NAND2_X1 _175_ (
    .A1(srcb[10]),
    .A2(_019_),
    .ZN(_021_)
  );
  OAI21_X1 _176_ (
    .A(srca[10]),
    .B1(_019_),
    .B2(srcb[10]),
    .ZN(_022_)
  );
  AOI21_X1 _177_ (
    .A(_072_),
    .B1(_021_),
    .B2(_022_),
    .ZN(_023_)
  );
  AND3_X1 _178_ (
    .A1(_072_),
    .A2(_021_),
    .A3(_022_),
    .ZN(_024_)
  );
  NAND3_X1 _179_ (
    .A1(_072_),
    .A2(_021_),
    .A3(_022_),
    .ZN(_025_)
  );
  OAI21_X1 _180_ (
    .A(_025_),
    .B1(_023_),
    .B2(srca[11]),
    .ZN(_026_)
  );
  NAND2_X1 _181_ (
    .A1(_073_),
    .A2(_026_),
    .ZN(_027_)
  );
  OAI211_X1 _182_ (
    .A(srcb[12]),
    .B(_025_),
    .C1(_023_),
    .C2(srca[11]),
    .ZN(_028_)
  );
  NAND2_X1 _183_ (
    .A1(_074_),
    .A2(_028_),
    .ZN(_029_)
  );
  NAND3_X1 _184_ (
    .A1(srcb[13]),
    .A2(_027_),
    .A3(_029_),
    .ZN(_030_)
  );
  AOI21_X1 _185_ (
    .A(srcb[13]),
    .B1(_027_),
    .B2(_029_),
    .ZN(_031_)
  );
  AOI21_X1 _186_ (
    .A(_031_),
    .B1(_030_),
    .B2(_075_),
    .ZN(_032_)
  );
  NOR2_X1 _187_ (
    .A1(srcb[14]),
    .A2(_032_),
    .ZN(_033_)
  );
  XNOR2_X1 _188_ (
    .A(srcb[14]),
    .B(_032_),
    .ZN(_034_)
  );
  XNOR2_X1 _189_ (
    .A(srca[14]),
    .B(_034_),
    .ZN(\full_adders[14].adder.result )
  );
  AOI21_X1 _190_ (
    .A(srca[14]),
    .B1(_032_),
    .B2(srcb[14]),
    .ZN(_035_)
  );
  OR2_X1 _191_ (
    .A1(_033_),
    .A2(_035_),
    .ZN(_036_)
  );
  NOR2_X1 _192_ (
    .A1(srca[15]),
    .A2(srcb[15]),
    .ZN(_037_)
  );
  NAND2_X1 _193_ (
    .A1(srca[15]),
    .A2(srcb[15]),
    .ZN(_038_)
  );
  XOR2_X1 _194_ (
    .A(srca[15]),
    .B(srcb[15]),
    .Z(_039_)
  );
  AOI21_X1 _195_ (
    .A(_037_),
    .B1(_038_),
    .B2(_036_),
    .ZN(cout)
  );
  XNOR2_X1 _196_ (
    .A(_036_),
    .B(_039_),
    .ZN(\full_adders[15].adder.result )
  );
  AND2_X1 _197_ (
    .A1(_027_),
    .A2(_028_),
    .ZN(_040_)
  );
  XNOR2_X1 _198_ (
    .A(_074_),
    .B(_040_),
    .ZN(\full_adders[12].adder.result )
  );
  AND2_X1 _199_ (
    .A1(_075_),
    .A2(_031_),
    .ZN(_041_)
  );
  OAI22_X1 _200_ (
    .A1(_075_),
    .A2(_030_),
    .B1(_032_),
    .B2(_041_),
    .ZN(\full_adders[13].adder.result )
  );
  AND2_X1 _201_ (
    .A1(_020_),
    .A2(_021_),
    .ZN(_042_)
  );
  XNOR2_X1 _202_ (
    .A(_071_),
    .B(_042_),
    .ZN(\full_adders[10].adder.result )
  );
  NOR2_X1 _203_ (
    .A1(_023_),
    .A2(_024_),
    .ZN(_043_)
  );
  XOR2_X1 _204_ (
    .A(srca[11]),
    .B(_043_),
    .Z(\full_adders[11].adder.result )
  );
  AND2_X1 _205_ (
    .A1(_014_),
    .A2(_015_),
    .ZN(_044_)
  );
  XNOR2_X1 _206_ (
    .A(_069_),
    .B(_044_),
    .ZN(\full_adders[8].adder.result )
  );
  AND2_X1 _207_ (
    .A1(_070_),
    .A2(_018_),
    .ZN(_045_)
  );
  OAI22_X1 _208_ (
    .A1(_070_),
    .A2(_017_),
    .B1(_019_),
    .B2(_045_),
    .ZN(\full_adders[9].adder.result )
  );
  AND2_X1 _209_ (
    .A1(_005_),
    .A2(_006_),
    .ZN(_046_)
  );
  XNOR2_X1 _210_ (
    .A(_066_),
    .B(_046_),
    .ZN(\full_adders[6].adder.result )
  );
  OAI21_X1 _211_ (
    .A(srca[7]),
    .B1(_009_),
    .B2(_011_),
    .ZN(_047_)
  );
  OAI21_X1 _212_ (
    .A(_047_),
    .B1(_013_),
    .B2(_011_),
    .ZN(\full_adders[7].adder.result )
  );
  XNOR2_X1 _213_ (
    .A(_062_),
    .B(_102_),
    .ZN(_048_)
  );
  XNOR2_X1 _214_ (
    .A(srca[4]),
    .B(_048_),
    .ZN(\full_adders[4].adder.result )
  );
  AOI21_X1 _215_ (
    .A(srca[5]),
    .B1(_001_),
    .B2(_003_),
    .ZN(_049_)
  );
  AOI21_X1 _216_ (
    .A(_049_),
    .B1(_004_),
    .B2(_001_),
    .ZN(\full_adders[5].adder.result )
  );
  NOR3_X1 _217_ (
    .A1(_076_),
    .A2(_082_),
    .A3(_093_),
    .ZN(_050_)
  );
  NOR3_X1 _218_ (
    .A1(_094_),
    .A2(_096_),
    .A3(_050_),
    .ZN(_051_)
  );
  AOI21_X1 _219_ (
    .A(_051_),
    .B1(_094_),
    .B2(_076_),
    .ZN(\full_adders[2].adder.result )
  );
  AOI21_X1 _220_ (
    .A(srca[3]),
    .B1(_099_),
    .B2(_101_),
    .ZN(_052_)
  );
  AOI21_X1 _221_ (
    .A(_052_),
    .B1(_103_),
    .B2(_099_),
    .ZN(\full_adders[3].adder.result )
  );
  OAI21_X1 _222_ (
    .A(_087_),
    .B1(srcb[0]),
    .B2(cin),
    .ZN(_053_)
  );
  AOI21_X1 _223_ (
    .A(_086_),
    .B1(srcb[0]),
    .B2(cin),
    .ZN(_054_)
  );
  AOI21_X1 _224_ (
    .A(_054_),
    .B1(_053_),
    .B2(_078_),
    .ZN(\full_adders[0].adder.result )
  );
  NOR2_X1 _225_ (
    .A1(srca[1]),
    .A2(_089_),
    .ZN(_055_)
  );
  OAI22_X1 _226_ (
    .A1(_079_),
    .A2(_091_),
    .B1(_092_),
    .B2(_055_),
    .ZN(\full_adders[1].adder.result )
  );
  OR4_X1 _227_ (
    .A1(\full_adders[4].adder.result ),
    .A2(\full_adders[2].adder.result ),
    .A3(\full_adders[0].adder.result ),
    .A4(\full_adders[1].adder.result ),
    .ZN(_056_)
  );
  OR4_X1 _228_ (
    .A1(\full_adders[6].adder.result ),
    .A2(\full_adders[5].adder.result ),
    .A3(\full_adders[3].adder.result ),
    .A4(_056_),
    .ZN(_057_)
  );
  OR3_X1 _229_ (
    .A1(\full_adders[8].adder.result ),
    .A2(\full_adders[7].adder.result ),
    .A3(_057_),
    .ZN(_058_)
  );
  OR4_X1 _230_ (
    .A1(\full_adders[10].adder.result ),
    .A2(\full_adders[11].adder.result ),
    .A3(\full_adders[9].adder.result ),
    .A4(_058_),
    .ZN(_059_)
  );
  OR3_X1 _231_ (
    .A1(\full_adders[12].adder.result ),
    .A2(\full_adders[13].adder.result ),
    .A3(_059_),
    .ZN(_060_)
  );
  NOR3_X1 _232_ (
    .A1(\full_adders[14].adder.result ),
    .A2(\full_adders[15].adder.result ),
    .A3(_060_),
    .ZN(zero_f)
  );
  OR2_X1 _233_ (
    .A1(_080_),
    .A2(_036_),
    .ZN(_061_)
  );
  MUX2_X1 _234_ (
    .A(_037_),
    .B(cout),
    .S(_061_),
    .Z(ov_f)
  );
  assign result = { \full_adders[15].adder.result , \full_adders[14].adder.result , \full_adders[13].adder.result , \full_adders[12].adder.result , \full_adders[11].adder.result , \full_adders[10].adder.result , \full_adders[9].adder.result , \full_adders[8].adder.result , \full_adders[7].adder.result , \full_adders[6].adder.result , \full_adders[5].adder.result , \full_adders[4].adder.result , \full_adders[3].adder.result , \full_adders[2].adder.result , \full_adders[1].adder.result , \full_adders[0].adder.result  };
endmodule
