/* Generated by Yosys 0.66+4 (git sha1 8125af88d-dirty, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

module adder(srca, srcb, cin, is_signed, result, cout, zero_f, ov_f);
  input [31:0] srca;
  wire [31:0] srca;
  input [31:0] srcb;
  wire [31:0] srcb;
  input cin;
  wire cin;
  input is_signed;
  wire is_signed;
  output [31:0] result;
  wire [31:0] result;
  output cout;
  wire cout;
  output zero_f;
  wire zero_f;
  output ov_f;
  wire ov_f;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire \full_adders[0].adder.result ;
  wire \full_adders[10].adder.result ;
  wire \full_adders[11].adder.result ;
  wire \full_adders[12].adder.result ;
  wire \full_adders[13].adder.result ;
  wire \full_adders[14].adder.result ;
  wire \full_adders[15].adder.result ;
  wire \full_adders[16].adder.result ;
  wire \full_adders[17].adder.result ;
  wire \full_adders[18].adder.result ;
  wire \full_adders[19].adder.result ;
  wire \full_adders[1].adder.result ;
  wire \full_adders[20].adder.result ;
  wire \full_adders[21].adder.result ;
  wire \full_adders[22].adder.result ;
  wire \full_adders[23].adder.result ;
  wire \full_adders[24].adder.result ;
  wire \full_adders[25].adder.result ;
  wire \full_adders[26].adder.result ;
  wire \full_adders[27].adder.result ;
  wire \full_adders[28].adder.result ;
  wire \full_adders[29].adder.result ;
  wire \full_adders[2].adder.result ;
  wire \full_adders[30].adder.result ;
  wire \full_adders[31].adder.result ;
  wire \full_adders[3].adder.result ;
  wire \full_adders[4].adder.result ;
  wire \full_adders[5].adder.result ;
  wire \full_adders[6].adder.result ;
  wire \full_adders[7].adder.result ;
  wire \full_adders[8].adder.result ;
  wire \full_adders[9].adder.result ;
  INV_X1 _225_ (
    .A(srcb[8]),
    .ZN(_000_)
  );
  INV_X1 _226_ (
    .A(srca[8]),
    .ZN(_001_)
  );
  INV_X1 _227_ (
    .A(srcb[9]),
    .ZN(_002_)
  );
  INV_X1 _228_ (
    .A(srca[9]),
    .ZN(_003_)
  );
  INV_X1 _229_ (
    .A(srca[10]),
    .ZN(_004_)
  );
  INV_X1 _230_ (
    .A(srcb[11]),
    .ZN(_005_)
  );
  INV_X1 _231_ (
    .A(srca[11]),
    .ZN(_006_)
  );
  INV_X1 _232_ (
    .A(srcb[12]),
    .ZN(_007_)
  );
  INV_X1 _233_ (
    .A(srca[12]),
    .ZN(_008_)
  );
  INV_X1 _234_ (
    .A(srcb[13]),
    .ZN(_009_)
  );
  INV_X1 _235_ (
    .A(srca[13]),
    .ZN(_010_)
  );
  INV_X1 _236_ (
    .A(srca[14]),
    .ZN(_011_)
  );
  INV_X1 _237_ (
    .A(srcb[15]),
    .ZN(_012_)
  );
  INV_X1 _238_ (
    .A(srca[15]),
    .ZN(_013_)
  );
  INV_X1 _239_ (
    .A(srcb[16]),
    .ZN(_014_)
  );
  INV_X1 _240_ (
    .A(srca[16]),
    .ZN(_015_)
  );
  INV_X1 _241_ (
    .A(srcb[17]),
    .ZN(_016_)
  );
  INV_X1 _242_ (
    .A(srca[17]),
    .ZN(_017_)
  );
  INV_X1 _243_ (
    .A(srca[18]),
    .ZN(_018_)
  );
  INV_X1 _244_ (
    .A(srcb[19]),
    .ZN(_019_)
  );
  INV_X1 _245_ (
    .A(srca[19]),
    .ZN(_020_)
  );
  INV_X1 _246_ (
    .A(srcb[20]),
    .ZN(_021_)
  );
  INV_X1 _247_ (
    .A(srca[20]),
    .ZN(_022_)
  );
  INV_X1 _248_ (
    .A(srcb[21]),
    .ZN(_023_)
  );
  INV_X1 _249_ (
    .A(srca[21]),
    .ZN(_024_)
  );
  INV_X1 _250_ (
    .A(srca[22]),
    .ZN(_025_)
  );
  INV_X1 _251_ (
    .A(srcb[23]),
    .ZN(_026_)
  );
  INV_X1 _252_ (
    .A(srca[23]),
    .ZN(_027_)
  );
  INV_X1 _253_ (
    .A(srcb[24]),
    .ZN(_028_)
  );
  INV_X1 _254_ (
    .A(srca[24]),
    .ZN(_029_)
  );
  INV_X1 _255_ (
    .A(srcb[25]),
    .ZN(_030_)
  );
  INV_X1 _256_ (
    .A(srca[25]),
    .ZN(_031_)
  );
  INV_X1 _257_ (
    .A(srca[26]),
    .ZN(_032_)
  );
  INV_X1 _258_ (
    .A(srcb[27]),
    .ZN(_033_)
  );
  INV_X1 _259_ (
    .A(srca[27]),
    .ZN(_034_)
  );
  INV_X1 _260_ (
    .A(srcb[29]),
    .ZN(_035_)
  );
  INV_X1 _261_ (
    .A(srcb[30]),
    .ZN(_036_)
  );
  INV_X1 _262_ (
    .A(srca[30]),
    .ZN(_037_)
  );
  INV_X1 _263_ (
    .A(srca[7]),
    .ZN(_038_)
  );
  INV_X1 _264_ (
    .A(srca[4]),
    .ZN(_039_)
  );
  INV_X1 _265_ (
    .A(srca[5]),
    .ZN(_040_)
  );
  INV_X1 _266_ (
    .A(srca[2]),
    .ZN(_041_)
  );
  INV_X1 _267_ (
    .A(srca[0]),
    .ZN(_042_)
  );
  INV_X1 _268_ (
    .A(srca[1]),
    .ZN(_043_)
  );
  INV_X1 _269_ (
    .A(srcb[7]),
    .ZN(_044_)
  );
  INV_X1 _270_ (
    .A(srcb[6]),
    .ZN(_045_)
  );
  INV_X1 _271_ (
    .A(srcb[3]),
    .ZN(_046_)
  );
  INV_X1 _272_ (
    .A(srcb[1]),
    .ZN(_047_)
  );
  INV_X1 _273_ (
    .A(srcb[4]),
    .ZN(_048_)
  );
  NAND2_X1 _274_ (
    .A1(cin),
    .A2(srcb[0]),
    .ZN(_049_)
  );
  NOR2_X1 _275_ (
    .A1(cin),
    .A2(srcb[0]),
    .ZN(_050_)
  );
  OAI21_X1 _276_ (
    .A(srca[0]),
    .B1(cin),
    .B2(srcb[0]),
    .ZN(_051_)
  );
  AOI21_X1 _277_ (
    .A(srca[0]),
    .B1(cin),
    .B2(srcb[0]),
    .ZN(_052_)
  );
  AND3_X1 _278_ (
    .A1(_047_),
    .A2(_049_),
    .A3(_051_),
    .ZN(_053_)
  );
  OR3_X1 _279_ (
    .A1(_047_),
    .A2(_050_),
    .A3(_052_),
    .ZN(_054_)
  );
  OAI21_X1 _280_ (
    .A(_054_),
    .B1(_053_),
    .B2(_043_),
    .ZN(_055_)
  );
  NOR2_X1 _281_ (
    .A1(srcb[2]),
    .A2(_055_),
    .ZN(_056_)
  );
  AOI21_X1 _282_ (
    .A(srca[2]),
    .B1(srcb[2]),
    .B2(_055_),
    .ZN(_057_)
  );
  NOR2_X1 _283_ (
    .A1(_056_),
    .A2(_057_),
    .ZN(_058_)
  );
  NOR3_X1 _284_ (
    .A1(_046_),
    .A2(_056_),
    .A3(_057_),
    .ZN(_059_)
  );
  OAI21_X1 _285_ (
    .A(_046_),
    .B1(_056_),
    .B2(_057_),
    .ZN(_060_)
  );
  OAI21_X1 _286_ (
    .A(_060_),
    .B1(_059_),
    .B2(srca[3]),
    .ZN(_061_)
  );
  OAI211_X1 _287_ (
    .A(srcb[4]),
    .B(_060_),
    .C1(_059_),
    .C2(srca[3]),
    .ZN(_062_)
  );
  NAND2_X1 _288_ (
    .A1(_048_),
    .A2(_061_),
    .ZN(_063_)
  );
  NAND2_X1 _289_ (
    .A1(_039_),
    .A2(_062_),
    .ZN(_064_)
  );
  AND3_X1 _290_ (
    .A1(srcb[5]),
    .A2(_063_),
    .A3(_064_),
    .ZN(_065_)
  );
  NAND3_X1 _291_ (
    .A1(srcb[5]),
    .A2(_063_),
    .A3(_064_),
    .ZN(_066_)
  );
  AOI21_X1 _292_ (
    .A(srcb[5]),
    .B1(_063_),
    .B2(_064_),
    .ZN(_067_)
  );
  NOR2_X1 _293_ (
    .A1(_040_),
    .A2(_067_),
    .ZN(_068_)
  );
  AOI211_X1 _294_ (
    .A(_045_),
    .B(_067_),
    .C1(_066_),
    .C2(_040_),
    .ZN(_069_)
  );
  NOR3_X1 _295_ (
    .A1(srcb[6]),
    .A2(_065_),
    .A3(_068_),
    .ZN(_070_)
  );
  OR3_X1 _296_ (
    .A1(srcb[6]),
    .A2(_065_),
    .A3(_068_),
    .ZN(_071_)
  );
  NOR2_X1 _297_ (
    .A1(srca[6]),
    .A2(_069_),
    .ZN(_072_)
  );
  OR2_X1 _298_ (
    .A1(srca[6]),
    .A2(_069_),
    .ZN(_073_)
  );
  AOI21_X1 _299_ (
    .A(srcb[7]),
    .B1(_071_),
    .B2(_073_),
    .ZN(_074_)
  );
  OAI21_X1 _300_ (
    .A(_044_),
    .B1(_070_),
    .B2(_072_),
    .ZN(_075_)
  );
  NOR3_X1 _301_ (
    .A1(_044_),
    .A2(_070_),
    .A3(_072_),
    .ZN(_076_)
  );
  NAND3_X1 _302_ (
    .A1(srcb[7]),
    .A2(_071_),
    .A3(_073_),
    .ZN(_077_)
  );
  OAI21_X1 _303_ (
    .A(_077_),
    .B1(_074_),
    .B2(_038_),
    .ZN(_078_)
  );
  AOI21_X1 _304_ (
    .A(_076_),
    .B1(_075_),
    .B2(srca[7]),
    .ZN(_079_)
  );
  NOR2_X1 _305_ (
    .A1(srcb[8]),
    .A2(_078_),
    .ZN(_080_)
  );
  NAND2_X1 _306_ (
    .A1(_000_),
    .A2(_079_),
    .ZN(_081_)
  );
  AOI21_X1 _307_ (
    .A(srca[8]),
    .B1(_078_),
    .B2(srcb[8]),
    .ZN(_082_)
  );
  OAI21_X1 _308_ (
    .A(_001_),
    .B1(_079_),
    .B2(_000_),
    .ZN(_083_)
  );
  AOI21_X1 _309_ (
    .A(srcb[9]),
    .B1(_081_),
    .B2(_083_),
    .ZN(_084_)
  );
  OAI21_X1 _310_ (
    .A(_002_),
    .B1(_080_),
    .B2(_082_),
    .ZN(_085_)
  );
  NOR3_X1 _311_ (
    .A1(_002_),
    .A2(_080_),
    .A3(_082_),
    .ZN(_086_)
  );
  NAND3_X1 _312_ (
    .A1(srcb[9]),
    .A2(_081_),
    .A3(_083_),
    .ZN(_087_)
  );
  OAI21_X1 _313_ (
    .A(_087_),
    .B1(_084_),
    .B2(_003_),
    .ZN(_088_)
  );
  AOI211_X1 _314_ (
    .A(srcb[10]),
    .B(_086_),
    .C1(_085_),
    .C2(srca[9]),
    .ZN(_089_)
  );
  NOR2_X1 _315_ (
    .A1(_004_),
    .A2(_089_),
    .ZN(_090_)
  );
  AOI21_X1 _316_ (
    .A(srca[10]),
    .B1(_088_),
    .B2(srcb[10]),
    .ZN(_091_)
  );
  AOI211_X1 _317_ (
    .A(srcb[11]),
    .B(_090_),
    .C1(_088_),
    .C2(srcb[10]),
    .ZN(_092_)
  );
  OAI21_X1 _318_ (
    .A(_005_),
    .B1(_089_),
    .B2(_091_),
    .ZN(_093_)
  );
  NOR3_X1 _319_ (
    .A1(_005_),
    .A2(_089_),
    .A3(_091_),
    .ZN(_094_)
  );
  OR3_X1 _320_ (
    .A1(_005_),
    .A2(_089_),
    .A3(_091_),
    .ZN(_095_)
  );
  OAI21_X1 _321_ (
    .A(_095_),
    .B1(_092_),
    .B2(_006_),
    .ZN(_096_)
  );
  AOI21_X1 _322_ (
    .A(_094_),
    .B1(_093_),
    .B2(srca[11]),
    .ZN(_097_)
  );
  NOR2_X1 _323_ (
    .A1(srcb[12]),
    .A2(_096_),
    .ZN(_098_)
  );
  NAND2_X1 _324_ (
    .A1(_007_),
    .A2(_097_),
    .ZN(_099_)
  );
  AOI21_X1 _325_ (
    .A(srca[12]),
    .B1(_096_),
    .B2(srcb[12]),
    .ZN(_100_)
  );
  OAI21_X1 _326_ (
    .A(_008_),
    .B1(_097_),
    .B2(_007_),
    .ZN(_101_)
  );
  AOI21_X1 _327_ (
    .A(srcb[13]),
    .B1(_099_),
    .B2(_101_),
    .ZN(_102_)
  );
  OAI21_X1 _328_ (
    .A(_009_),
    .B1(_098_),
    .B2(_100_),
    .ZN(_103_)
  );
  NOR3_X1 _329_ (
    .A1(_009_),
    .A2(_098_),
    .A3(_100_),
    .ZN(_104_)
  );
  NAND3_X1 _330_ (
    .A1(srcb[13]),
    .A2(_099_),
    .A3(_101_),
    .ZN(_105_)
  );
  OAI21_X1 _331_ (
    .A(_105_),
    .B1(_102_),
    .B2(_010_),
    .ZN(_106_)
  );
  AOI211_X1 _332_ (
    .A(srcb[14]),
    .B(_104_),
    .C1(_103_),
    .C2(srca[13]),
    .ZN(_107_)
  );
  NOR2_X1 _333_ (
    .A1(_011_),
    .A2(_107_),
    .ZN(_108_)
  );
  AOI21_X1 _334_ (
    .A(srca[14]),
    .B1(_106_),
    .B2(srcb[14]),
    .ZN(_109_)
  );
  AOI211_X1 _335_ (
    .A(srcb[15]),
    .B(_108_),
    .C1(_106_),
    .C2(srcb[14]),
    .ZN(_110_)
  );
  OAI21_X1 _336_ (
    .A(_012_),
    .B1(_107_),
    .B2(_109_),
    .ZN(_111_)
  );
  NOR3_X1 _337_ (
    .A1(_012_),
    .A2(_107_),
    .A3(_109_),
    .ZN(_112_)
  );
  OR3_X1 _338_ (
    .A1(_012_),
    .A2(_107_),
    .A3(_109_),
    .ZN(_113_)
  );
  OAI21_X1 _339_ (
    .A(_113_),
    .B1(_110_),
    .B2(_013_),
    .ZN(_114_)
  );
  AOI21_X1 _340_ (
    .A(_112_),
    .B1(_111_),
    .B2(srca[15]),
    .ZN(_115_)
  );
  NOR2_X1 _341_ (
    .A1(srcb[16]),
    .A2(_114_),
    .ZN(_116_)
  );
  NAND2_X1 _342_ (
    .A1(_014_),
    .A2(_115_),
    .ZN(_117_)
  );
  AOI21_X1 _343_ (
    .A(srca[16]),
    .B1(_114_),
    .B2(srcb[16]),
    .ZN(_118_)
  );
  OAI21_X1 _344_ (
    .A(_015_),
    .B1(_115_),
    .B2(_014_),
    .ZN(_119_)
  );
  AOI21_X1 _345_ (
    .A(srcb[17]),
    .B1(_117_),
    .B2(_119_),
    .ZN(_120_)
  );
  OAI21_X1 _346_ (
    .A(_016_),
    .B1(_116_),
    .B2(_118_),
    .ZN(_121_)
  );
  NOR3_X1 _347_ (
    .A1(_016_),
    .A2(_116_),
    .A3(_118_),
    .ZN(_122_)
  );
  NAND3_X1 _348_ (
    .A1(srcb[17]),
    .A2(_117_),
    .A3(_119_),
    .ZN(_123_)
  );
  OAI21_X1 _349_ (
    .A(_123_),
    .B1(_120_),
    .B2(_017_),
    .ZN(_124_)
  );
  AOI211_X1 _350_ (
    .A(srcb[18]),
    .B(_122_),
    .C1(_121_),
    .C2(srca[17]),
    .ZN(_125_)
  );
  NOR2_X1 _351_ (
    .A1(_018_),
    .A2(_125_),
    .ZN(_126_)
  );
  AOI21_X1 _352_ (
    .A(srca[18]),
    .B1(_124_),
    .B2(srcb[18]),
    .ZN(_127_)
  );
  AOI211_X1 _353_ (
    .A(srcb[19]),
    .B(_126_),
    .C1(_124_),
    .C2(srcb[18]),
    .ZN(_128_)
  );
  OAI21_X1 _354_ (
    .A(_019_),
    .B1(_125_),
    .B2(_127_),
    .ZN(_129_)
  );
  NOR3_X1 _355_ (
    .A1(_019_),
    .A2(_125_),
    .A3(_127_),
    .ZN(_130_)
  );
  OR3_X1 _356_ (
    .A1(_019_),
    .A2(_125_),
    .A3(_127_),
    .ZN(_131_)
  );
  OAI21_X1 _357_ (
    .A(_131_),
    .B1(_128_),
    .B2(_020_),
    .ZN(_132_)
  );
  AOI21_X1 _358_ (
    .A(_130_),
    .B1(_129_),
    .B2(srca[19]),
    .ZN(_133_)
  );
  NOR2_X1 _359_ (
    .A1(srcb[20]),
    .A2(_132_),
    .ZN(_134_)
  );
  NAND2_X1 _360_ (
    .A1(_021_),
    .A2(_133_),
    .ZN(_135_)
  );
  AOI21_X1 _361_ (
    .A(srca[20]),
    .B1(_132_),
    .B2(srcb[20]),
    .ZN(_136_)
  );
  OAI21_X1 _362_ (
    .A(_022_),
    .B1(_133_),
    .B2(_021_),
    .ZN(_137_)
  );
  AOI21_X1 _363_ (
    .A(srcb[21]),
    .B1(_135_),
    .B2(_137_),
    .ZN(_138_)
  );
  OAI21_X1 _364_ (
    .A(_023_),
    .B1(_134_),
    .B2(_136_),
    .ZN(_139_)
  );
  NOR3_X1 _365_ (
    .A1(_023_),
    .A2(_134_),
    .A3(_136_),
    .ZN(_140_)
  );
  NAND3_X1 _366_ (
    .A1(srcb[21]),
    .A2(_135_),
    .A3(_137_),
    .ZN(_141_)
  );
  OAI21_X1 _367_ (
    .A(_141_),
    .B1(_138_),
    .B2(_024_),
    .ZN(_142_)
  );
  AOI211_X1 _368_ (
    .A(srcb[22]),
    .B(_140_),
    .C1(_139_),
    .C2(srca[21]),
    .ZN(_143_)
  );
  NOR2_X1 _369_ (
    .A1(_025_),
    .A2(_143_),
    .ZN(_144_)
  );
  AOI21_X1 _370_ (
    .A(srca[22]),
    .B1(_142_),
    .B2(srcb[22]),
    .ZN(_145_)
  );
  AOI211_X1 _371_ (
    .A(srcb[23]),
    .B(_144_),
    .C1(_142_),
    .C2(srcb[22]),
    .ZN(_146_)
  );
  OAI21_X1 _372_ (
    .A(_026_),
    .B1(_143_),
    .B2(_145_),
    .ZN(_147_)
  );
  NOR3_X1 _373_ (
    .A1(_026_),
    .A2(_143_),
    .A3(_145_),
    .ZN(_148_)
  );
  OR3_X1 _374_ (
    .A1(_026_),
    .A2(_143_),
    .A3(_145_),
    .ZN(_149_)
  );
  OAI21_X1 _375_ (
    .A(_149_),
    .B1(_146_),
    .B2(_027_),
    .ZN(_150_)
  );
  AOI21_X1 _376_ (
    .A(_148_),
    .B1(_147_),
    .B2(srca[23]),
    .ZN(_151_)
  );
  NOR2_X1 _377_ (
    .A1(srcb[24]),
    .A2(_150_),
    .ZN(_152_)
  );
  NAND2_X1 _378_ (
    .A1(_028_),
    .A2(_151_),
    .ZN(_153_)
  );
  AOI21_X1 _379_ (
    .A(srca[24]),
    .B1(_150_),
    .B2(srcb[24]),
    .ZN(_154_)
  );
  OAI21_X1 _380_ (
    .A(_029_),
    .B1(_151_),
    .B2(_028_),
    .ZN(_155_)
  );
  AOI21_X1 _381_ (
    .A(srcb[25]),
    .B1(_153_),
    .B2(_155_),
    .ZN(_156_)
  );
  OAI21_X1 _382_ (
    .A(_030_),
    .B1(_152_),
    .B2(_154_),
    .ZN(_157_)
  );
  NOR3_X1 _383_ (
    .A1(_030_),
    .A2(_152_),
    .A3(_154_),
    .ZN(_158_)
  );
  NAND3_X1 _384_ (
    .A1(srcb[25]),
    .A2(_153_),
    .A3(_155_),
    .ZN(_159_)
  );
  OAI21_X1 _385_ (
    .A(_159_),
    .B1(_156_),
    .B2(_031_),
    .ZN(_160_)
  );
  AOI211_X1 _386_ (
    .A(srcb[26]),
    .B(_158_),
    .C1(_157_),
    .C2(srca[25]),
    .ZN(_161_)
  );
  NOR2_X1 _387_ (
    .A1(_032_),
    .A2(_161_),
    .ZN(_162_)
  );
  AOI21_X1 _388_ (
    .A(srca[26]),
    .B1(_160_),
    .B2(srcb[26]),
    .ZN(_163_)
  );
  AOI211_X1 _389_ (
    .A(srcb[27]),
    .B(_162_),
    .C1(_160_),
    .C2(srcb[26]),
    .ZN(_164_)
  );
  OR3_X1 _390_ (
    .A1(_033_),
    .A2(_161_),
    .A3(_163_),
    .ZN(_165_)
  );
  OAI21_X1 _391_ (
    .A(_165_),
    .B1(_164_),
    .B2(_034_),
    .ZN(_166_)
  );
  NOR2_X1 _392_ (
    .A1(srcb[28]),
    .A2(_166_),
    .ZN(_167_)
  );
  AOI21_X1 _393_ (
    .A(srca[28]),
    .B1(_166_),
    .B2(srcb[28]),
    .ZN(_168_)
  );
  OAI21_X1 _394_ (
    .A(_035_),
    .B1(_167_),
    .B2(_168_),
    .ZN(_169_)
  );
  NOR3_X1 _395_ (
    .A1(_035_),
    .A2(_167_),
    .A3(_168_),
    .ZN(_170_)
  );
  AOI21_X1 _396_ (
    .A(_170_),
    .B1(_169_),
    .B2(srca[29]),
    .ZN(_171_)
  );
  NOR2_X1 _397_ (
    .A1(_036_),
    .A2(_171_),
    .ZN(_172_)
  );
  XNOR2_X1 _398_ (
    .A(srcb[30]),
    .B(_171_),
    .ZN(_173_)
  );
  AOI21_X1 _399_ (
    .A(_037_),
    .B1(_171_),
    .B2(_036_),
    .ZN(_174_)
  );
  OR2_X1 _400_ (
    .A1(_172_),
    .A2(_174_),
    .ZN(_175_)
  );
  XNOR2_X1 _401_ (
    .A(_037_),
    .B(_173_),
    .ZN(\full_adders[30].adder.result )
  );
  NOR2_X1 _402_ (
    .A1(srca[31]),
    .A2(srcb[31]),
    .ZN(_176_)
  );
  XNOR2_X1 _403_ (
    .A(srca[31]),
    .B(srcb[31]),
    .ZN(_177_)
  );
  XNOR2_X1 _404_ (
    .A(_175_),
    .B(_177_),
    .ZN(\full_adders[31].adder.result )
  );
  XNOR2_X1 _405_ (
    .A(srcb[28]),
    .B(_166_),
    .ZN(_178_)
  );
  XNOR2_X1 _406_ (
    .A(srca[28]),
    .B(_178_),
    .ZN(\full_adders[28].adder.result )
  );
  NAND2_X1 _407_ (
    .A1(srca[29]),
    .A2(_170_),
    .ZN(_179_)
  );
  OAI21_X1 _408_ (
    .A(_171_),
    .B1(_169_),
    .B2(srca[29]),
    .ZN(_180_)
  );
  NAND2_X1 _409_ (
    .A1(_179_),
    .A2(_180_),
    .ZN(\full_adders[29].adder.result )
  );
  XNOR2_X1 _410_ (
    .A(srcb[26]),
    .B(_160_),
    .ZN(_181_)
  );
  XNOR2_X1 _411_ (
    .A(srca[26]),
    .B(_181_),
    .ZN(\full_adders[26].adder.result )
  );
  AND2_X1 _412_ (
    .A1(_034_),
    .A2(_164_),
    .ZN(_182_)
  );
  OAI22_X1 _413_ (
    .A1(_034_),
    .A2(_165_),
    .B1(_166_),
    .B2(_182_),
    .ZN(\full_adders[27].adder.result )
  );
  XNOR2_X1 _414_ (
    .A(_028_),
    .B(_150_),
    .ZN(_183_)
  );
  XNOR2_X1 _415_ (
    .A(_029_),
    .B(_183_),
    .ZN(\full_adders[24].adder.result )
  );
  NOR2_X1 _416_ (
    .A1(srca[25]),
    .A2(_157_),
    .ZN(_184_)
  );
  OAI22_X1 _417_ (
    .A1(_031_),
    .A2(_159_),
    .B1(_160_),
    .B2(_184_),
    .ZN(\full_adders[25].adder.result )
  );
  XNOR2_X1 _418_ (
    .A(srcb[22]),
    .B(_142_),
    .ZN(_185_)
  );
  XNOR2_X1 _419_ (
    .A(srca[22]),
    .B(_185_),
    .ZN(\full_adders[22].adder.result )
  );
  NOR2_X1 _420_ (
    .A1(srca[23]),
    .A2(_147_),
    .ZN(_186_)
  );
  OAI22_X1 _421_ (
    .A1(_027_),
    .A2(_149_),
    .B1(_150_),
    .B2(_186_),
    .ZN(\full_adders[23].adder.result )
  );
  XNOR2_X1 _422_ (
    .A(_021_),
    .B(_132_),
    .ZN(_187_)
  );
  XNOR2_X1 _423_ (
    .A(_022_),
    .B(_187_),
    .ZN(\full_adders[20].adder.result )
  );
  NOR2_X1 _424_ (
    .A1(srca[21]),
    .A2(_139_),
    .ZN(_188_)
  );
  OAI22_X1 _425_ (
    .A1(_024_),
    .A2(_141_),
    .B1(_142_),
    .B2(_188_),
    .ZN(\full_adders[21].adder.result )
  );
  XNOR2_X1 _426_ (
    .A(srcb[18]),
    .B(_124_),
    .ZN(_189_)
  );
  XNOR2_X1 _427_ (
    .A(srca[18]),
    .B(_189_),
    .ZN(\full_adders[18].adder.result )
  );
  NOR2_X1 _428_ (
    .A1(srca[19]),
    .A2(_129_),
    .ZN(_190_)
  );
  OAI22_X1 _429_ (
    .A1(_020_),
    .A2(_131_),
    .B1(_132_),
    .B2(_190_),
    .ZN(\full_adders[19].adder.result )
  );
  XNOR2_X1 _430_ (
    .A(_014_),
    .B(_114_),
    .ZN(_191_)
  );
  XNOR2_X1 _431_ (
    .A(_015_),
    .B(_191_),
    .ZN(\full_adders[16].adder.result )
  );
  NOR2_X1 _432_ (
    .A1(srca[17]),
    .A2(_121_),
    .ZN(_192_)
  );
  OAI22_X1 _433_ (
    .A1(_017_),
    .A2(_123_),
    .B1(_124_),
    .B2(_192_),
    .ZN(\full_adders[17].adder.result )
  );
  XOR2_X1 _434_ (
    .A(srcb[14]),
    .B(_106_),
    .Z(_193_)
  );
  XNOR2_X1 _435_ (
    .A(_011_),
    .B(_193_),
    .ZN(\full_adders[14].adder.result )
  );
  OAI21_X1 _436_ (
    .A(srca[15]),
    .B1(_110_),
    .B2(_112_),
    .ZN(_194_)
  );
  NAND3_X1 _437_ (
    .A1(_013_),
    .A2(_111_),
    .A3(_113_),
    .ZN(_195_)
  );
  NAND2_X1 _438_ (
    .A1(_194_),
    .A2(_195_),
    .ZN(\full_adders[15].adder.result )
  );
  XNOR2_X1 _439_ (
    .A(_007_),
    .B(_096_),
    .ZN(_196_)
  );
  XNOR2_X1 _440_ (
    .A(_008_),
    .B(_196_),
    .ZN(\full_adders[12].adder.result )
  );
  NOR2_X1 _441_ (
    .A1(srca[13]),
    .A2(_103_),
    .ZN(_197_)
  );
  OAI22_X1 _442_ (
    .A1(_010_),
    .A2(_105_),
    .B1(_106_),
    .B2(_197_),
    .ZN(\full_adders[13].adder.result )
  );
  XOR2_X1 _443_ (
    .A(srcb[10]),
    .B(_088_),
    .Z(_198_)
  );
  XNOR2_X1 _444_ (
    .A(_004_),
    .B(_198_),
    .ZN(\full_adders[10].adder.result )
  );
  OAI21_X1 _445_ (
    .A(srca[11]),
    .B1(_092_),
    .B2(_094_),
    .ZN(_199_)
  );
  NAND3_X1 _446_ (
    .A1(_006_),
    .A2(_093_),
    .A3(_095_),
    .ZN(_200_)
  );
  NAND2_X1 _447_ (
    .A1(_199_),
    .A2(_200_),
    .ZN(\full_adders[11].adder.result )
  );
  XNOR2_X1 _448_ (
    .A(_000_),
    .B(_078_),
    .ZN(_201_)
  );
  XNOR2_X1 _449_ (
    .A(_001_),
    .B(_201_),
    .ZN(\full_adders[8].adder.result )
  );
  NOR2_X1 _450_ (
    .A1(_084_),
    .A2(_086_),
    .ZN(_202_)
  );
  XNOR2_X1 _451_ (
    .A(_003_),
    .B(_202_),
    .ZN(\full_adders[9].adder.result )
  );
  NOR2_X1 _452_ (
    .A1(_069_),
    .A2(_070_),
    .ZN(_203_)
  );
  XOR2_X1 _453_ (
    .A(srca[6]),
    .B(_203_),
    .Z(\full_adders[6].adder.result )
  );
  NAND2_X1 _454_ (
    .A1(_075_),
    .A2(_077_),
    .ZN(_204_)
  );
  XNOR2_X1 _455_ (
    .A(srca[7]),
    .B(_204_),
    .ZN(\full_adders[7].adder.result )
  );
  AND2_X1 _456_ (
    .A1(_062_),
    .A2(_063_),
    .ZN(_205_)
  );
  XNOR2_X1 _457_ (
    .A(_039_),
    .B(_205_),
    .ZN(\full_adders[4].adder.result )
  );
  NOR2_X1 _458_ (
    .A1(_065_),
    .A2(_067_),
    .ZN(_206_)
  );
  XNOR2_X1 _459_ (
    .A(_040_),
    .B(_206_),
    .ZN(\full_adders[5].adder.result )
  );
  NAND3_X1 _460_ (
    .A1(srca[2]),
    .A2(srcb[2]),
    .A3(_055_),
    .ZN(_207_)
  );
  AOI22_X1 _461_ (
    .A1(_041_),
    .A2(_056_),
    .B1(_058_),
    .B2(_207_),
    .ZN(\full_adders[2].adder.result )
  );
  XNOR2_X1 _462_ (
    .A(srcb[3]),
    .B(_058_),
    .ZN(_208_)
  );
  XNOR2_X1 _463_ (
    .A(srca[3]),
    .B(_208_),
    .ZN(\full_adders[3].adder.result )
  );
  OAI21_X1 _464_ (
    .A(_052_),
    .B1(srcb[0]),
    .B2(cin),
    .ZN(_209_)
  );
  AOI21_X1 _465_ (
    .A(_051_),
    .B1(srcb[0]),
    .B2(cin),
    .ZN(_210_)
  );
  AOI21_X1 _466_ (
    .A(_210_),
    .B1(_209_),
    .B2(_042_),
    .ZN(\full_adders[0].adder.result )
  );
  AND2_X1 _467_ (
    .A1(_043_),
    .A2(_053_),
    .ZN(_211_)
  );
  OAI22_X1 _468_ (
    .A1(_043_),
    .A2(_054_),
    .B1(_055_),
    .B2(_211_),
    .ZN(\full_adders[1].adder.result )
  );
  AOI211_X1 _469_ (
    .A(_172_),
    .B(_174_),
    .C1(srca[31]),
    .C2(srcb[31]),
    .ZN(_212_)
  );
  NOR2_X1 _470_ (
    .A1(_176_),
    .A2(_212_),
    .ZN(cout)
  );
  OR4_X1 _471_ (
    .A1(\full_adders[2].adder.result ),
    .A2(\full_adders[3].adder.result ),
    .A3(\full_adders[0].adder.result ),
    .A4(\full_adders[1].adder.result ),
    .ZN(_213_)
  );
  OR4_X1 _472_ (
    .A1(\full_adders[6].adder.result ),
    .A2(\full_adders[4].adder.result ),
    .A3(\full_adders[5].adder.result ),
    .A4(_213_),
    .ZN(_214_)
  );
  OR4_X1 _473_ (
    .A1(\full_adders[8].adder.result ),
    .A2(\full_adders[9].adder.result ),
    .A3(\full_adders[7].adder.result ),
    .A4(_214_),
    .ZN(_215_)
  );
  OR4_X1 _474_ (
    .A1(\full_adders[13].adder.result ),
    .A2(\full_adders[10].adder.result ),
    .A3(\full_adders[11].adder.result ),
    .A4(_215_),
    .ZN(_216_)
  );
  OR3_X1 _475_ (
    .A1(\full_adders[15].adder.result ),
    .A2(\full_adders[12].adder.result ),
    .A3(_216_),
    .ZN(_217_)
  );
  OR4_X1 _476_ (
    .A1(\full_adders[16].adder.result ),
    .A2(\full_adders[17].adder.result ),
    .A3(\full_adders[14].adder.result ),
    .A4(_217_),
    .ZN(_218_)
  );
  OR4_X1 _477_ (
    .A1(\full_adders[20].adder.result ),
    .A2(\full_adders[18].adder.result ),
    .A3(\full_adders[19].adder.result ),
    .A4(_218_),
    .ZN(_219_)
  );
  OR2_X1 _478_ (
    .A1(\full_adders[21].adder.result ),
    .A2(_219_),
    .ZN(_220_)
  );
  OR4_X1 _479_ (
    .A1(\full_adders[24].adder.result ),
    .A2(\full_adders[22].adder.result ),
    .A3(\full_adders[23].adder.result ),
    .A4(_220_),
    .ZN(_221_)
  );
  OR2_X1 _480_ (
    .A1(\full_adders[25].adder.result ),
    .A2(_221_),
    .ZN(_222_)
  );
  OR4_X1 _481_ (
    .A1(\full_adders[28].adder.result ),
    .A2(\full_adders[26].adder.result ),
    .A3(\full_adders[27].adder.result ),
    .A4(_222_),
    .ZN(_223_)
  );
  NOR4_X1 _482_ (
    .A1(\full_adders[30].adder.result ),
    .A2(\full_adders[31].adder.result ),
    .A3(\full_adders[29].adder.result ),
    .A4(_223_),
    .ZN(zero_f)
  );
  NAND2_X1 _483_ (
    .A1(is_signed),
    .A2(_175_),
    .ZN(_224_)
  );
  MUX2_X1 _484_ (
    .A(_176_),
    .B(cout),
    .S(_224_),
    .Z(ov_f)
  );
  assign result = { \full_adders[31].adder.result , \full_adders[30].adder.result , \full_adders[29].adder.result , \full_adders[28].adder.result , \full_adders[27].adder.result , \full_adders[26].adder.result , \full_adders[25].adder.result , \full_adders[24].adder.result , \full_adders[23].adder.result , \full_adders[22].adder.result , \full_adders[21].adder.result , \full_adders[20].adder.result , \full_adders[19].adder.result , \full_adders[18].adder.result , \full_adders[17].adder.result , \full_adders[16].adder.result , \full_adders[15].adder.result , \full_adders[14].adder.result , \full_adders[13].adder.result , \full_adders[12].adder.result , \full_adders[11].adder.result , \full_adders[10].adder.result , \full_adders[9].adder.result , \full_adders[8].adder.result , \full_adders[7].adder.result , \full_adders[6].adder.result , \full_adders[5].adder.result , \full_adders[4].adder.result , \full_adders[3].adder.result , \full_adders[2].adder.result , \full_adders[1].adder.result , \full_adders[0].adder.result  };
endmodule
