/* Generated by Yosys 0.66+4 (git sha1 8125af88d-dirty, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* src = "convert_to_v/rca.v:1.1-38.10" *)
(* top =  1  *)
(* dynports =  1  *)
(* hdlname = "adder" *)
module adder(srca, srcb, cin, is_signed, result, cout, zero_f, ov_f);
  (* src = "convert_to_v/rca.v:12.27-12.31" *)
  input [31:0] srca;
  wire [31:0] srca;
  (* src = "convert_to_v/rca.v:13.27-13.31" *)
  input [31:0] srcb;
  wire [31:0] srcb;
  (* src = "convert_to_v/rca.v:14.13-14.16" *)
  input cin;
  wire cin;
  (* src = "convert_to_v/rca.v:15.13-15.22" *)
  input is_signed;
  wire is_signed;
  (* src = "convert_to_v/rca.v:16.28-16.34" *)
  output [31:0] result;
  wire [31:0] result;
  (* src = "convert_to_v/rca.v:17.14-17.18" *)
  output cout;
  wire cout;
  (* src = "convert_to_v/rca.v:18.14-18.20" *)
  output zero_f;
  wire zero_f;
  (* src = "convert_to_v/rca.v:19.14-19.18" *)
  output ov_f;
  wire ov_f;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  (* src = "convert_to_v/rca.v:20.17-20.18" *)
  wire [32:0] c;
  sky130_fd_sc_hd__nor4_1 _11_ (
    .A(result[8]),
    .B(result[14]),
    .C(result[2]),
    .D(result[4]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nor4_1 _12_ (
    .A(result[26]),
    .B(result[28]),
    .C(result[16]),
    .D(result[22]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nor4_1 _13_ (
    .A(result[10]),
    .B(result[12]),
    .C(result[0]),
    .D(result[6]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nor4_1 _14_ (
    .A(result[24]),
    .B(result[30]),
    .C(result[23]),
    .D(result[17]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nand4_1 _15_ (
    .A(_00_),
    .B(_01_),
    .C(_02_),
    .D(_03_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nor4_1 _16_ (
    .A(result[11]),
    .B(result[13]),
    .C(result[1]),
    .D(result[7]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nor4_1 _17_ (
    .A(result[25]),
    .B(result[31]),
    .C(result[19]),
    .D(result[21]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__nor4_1 _18_ (
    .A(result[9]),
    .B(result[15]),
    .C(result[3]),
    .D(result[5]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nor4_1 _19_ (
    .A(result[27]),
    .B(result[29]),
    .C(result[20]),
    .D(result[18]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nand4_1 _20_ (
    .A(_05_),
    .B(_06_),
    .C(_07_),
    .D(_08_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nor2_1 _21_ (
    .A(_04_),
    .B(_09_),
    .Y(zero_f)
  );
  sky130_fd_sc_hd__nand2_1 _22_ (
    .A(c[31]),
    .B(is_signed),
    .Y(_10_)
  );
  sky130_fd_sc_hd__xnor2_1 _23_ (
    .A(cout),
    .B(_10_),
    .Y(ov_f)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[0].adder  (
    .a(srca[0]),
    .b(srcb[0]),
    .cin(cin),
    .cout(c[1]),
    .result(result[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[10].adder  (
    .a(srca[10]),
    .b(srcb[10]),
    .cin(c[10]),
    .cout(c[11]),
    .result(result[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[11].adder  (
    .a(srca[11]),
    .b(srcb[11]),
    .cin(c[11]),
    .cout(c[12]),
    .result(result[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[12].adder  (
    .a(srca[12]),
    .b(srcb[12]),
    .cin(c[12]),
    .cout(c[13]),
    .result(result[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[13].adder  (
    .a(srca[13]),
    .b(srcb[13]),
    .cin(c[13]),
    .cout(c[14]),
    .result(result[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[14].adder  (
    .a(srca[14]),
    .b(srcb[14]),
    .cin(c[14]),
    .cout(c[15]),
    .result(result[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[15].adder  (
    .a(srca[15]),
    .b(srcb[15]),
    .cin(c[15]),
    .cout(c[16]),
    .result(result[15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[16].adder  (
    .a(srca[16]),
    .b(srcb[16]),
    .cin(c[16]),
    .cout(c[17]),
    .result(result[16])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[17].adder  (
    .a(srca[17]),
    .b(srcb[17]),
    .cin(c[17]),
    .cout(c[18]),
    .result(result[17])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[18].adder  (
    .a(srca[18]),
    .b(srcb[18]),
    .cin(c[18]),
    .cout(c[19]),
    .result(result[18])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[19].adder  (
    .a(srca[19]),
    .b(srcb[19]),
    .cin(c[19]),
    .cout(c[20]),
    .result(result[19])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[1].adder  (
    .a(srca[1]),
    .b(srcb[1]),
    .cin(c[1]),
    .cout(c[2]),
    .result(result[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[20].adder  (
    .a(srca[20]),
    .b(srcb[20]),
    .cin(c[20]),
    .cout(c[21]),
    .result(result[20])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[21].adder  (
    .a(srca[21]),
    .b(srcb[21]),
    .cin(c[21]),
    .cout(c[22]),
    .result(result[21])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[22].adder  (
    .a(srca[22]),
    .b(srcb[22]),
    .cin(c[22]),
    .cout(c[23]),
    .result(result[22])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[23].adder  (
    .a(srca[23]),
    .b(srcb[23]),
    .cin(c[23]),
    .cout(c[24]),
    .result(result[23])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[24].adder  (
    .a(srca[24]),
    .b(srcb[24]),
    .cin(c[24]),
    .cout(c[25]),
    .result(result[24])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[25].adder  (
    .a(srca[25]),
    .b(srcb[25]),
    .cin(c[25]),
    .cout(c[26]),
    .result(result[25])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[26].adder  (
    .a(srca[26]),
    .b(srcb[26]),
    .cin(c[26]),
    .cout(c[27]),
    .result(result[26])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[27].adder  (
    .a(srca[27]),
    .b(srcb[27]),
    .cin(c[27]),
    .cout(c[28]),
    .result(result[27])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[28].adder  (
    .a(srca[28]),
    .b(srcb[28]),
    .cin(c[28]),
    .cout(c[29]),
    .result(result[28])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[29].adder  (
    .a(srca[29]),
    .b(srcb[29]),
    .cin(c[29]),
    .cout(c[30]),
    .result(result[29])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[2].adder  (
    .a(srca[2]),
    .b(srcb[2]),
    .cin(c[2]),
    .cout(c[3]),
    .result(result[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[30].adder  (
    .a(srca[30]),
    .b(srcb[30]),
    .cin(c[30]),
    .cout(c[31]),
    .result(result[30])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[31].adder  (
    .a(srca[31]),
    .b(srcb[31]),
    .cin(c[31]),
    .cout(cout),
    .result(result[31])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[3].adder  (
    .a(srca[3]),
    .b(srcb[3]),
    .cin(c[3]),
    .cout(c[4]),
    .result(result[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[4].adder  (
    .a(srca[4]),
    .b(srcb[4]),
    .cin(c[4]),
    .cout(c[5]),
    .result(result[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[5].adder  (
    .a(srca[5]),
    .b(srcb[5]),
    .cin(c[5]),
    .cout(c[6]),
    .result(result[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[6].adder  (
    .a(srca[6]),
    .b(srcb[6]),
    .cin(c[6]),
    .cout(c[7]),
    .result(result[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[7].adder  (
    .a(srca[7]),
    .b(srcb[7]),
    .cin(c[7]),
    .cout(c[8]),
    .result(result[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[8].adder  (
    .a(srca[8]),
    .b(srcb[8]),
    .cin(c[8]),
    .cout(c[9]),
    .result(result[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "convert_to_v/rca.v:26.15-32.5" *)
  full_adder \full_adders[9].adder  (
    .a(srca[9]),
    .b(srcb[9]),
    .cin(c[9]),
    .cout(c[10]),
    .result(result[9])
  );
  assign { c[32], c[0] } = { cout, cin };
endmodule

(* src = "convert_to_v/full_adder.v:1.1-15.10" *)
module full_adder(a, b, cin, result, cout);
  (* src = "convert_to_v/full_adder.v:8.13-8.14" *)
  input a;
  wire a;
  (* src = "convert_to_v/full_adder.v:9.13-9.14" *)
  input b;
  wire b;
  (* src = "convert_to_v/full_adder.v:10.13-10.16" *)
  input cin;
  wire cin;
  (* src = "convert_to_v/full_adder.v:11.14-11.20" *)
  output result;
  wire result;
  (* src = "convert_to_v/full_adder.v:12.14-12.18" *)
  output cout;
  wire cout;
  sky130_fd_sc_hd__maj3_1 _0_ (
    .A(cin),
    .B(a),
    .C(b),
    .X(cout)
  );
  sky130_fd_sc_hd__xor3_1 _1_ (
    .A(cin),
    .B(a),
    .C(b),
    .X(result)
  );
endmodule
